apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: mcp
  labels:
    app.kubernetes.io/name: mcp
    app.kubernetes.io/part-of: mcp-project
    kubernetes.azure.com/generator: devhub
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: mcp